var cols = [
  { "name": "WO_NO", "title": "Nº OT", "default": true },
  { "name": "STATE", "title": "Estado", "default": true },
  { "name": "WO_NO_MADRE", "title": "OT Madre", "default": true },
  { "name": "REAL_F_DATE", "title": "Finalización Real", "default": true },
  { "name": "CONTRACT", "title": "Planta OT", "default": true },
  { "name": "SUBESTADO_PLANIF", "title": "Subestado planif", "default": true },
  { "name": "COM_INT_PLA", "title": "Com int pla", "default": true },
  { "name": "PLAN_F_DATE", "title": "Fin Prog", "default": true },
  { "name": "PLAN_S_DATE", "title": "Inicio Prog", "default": true },
  { "name": "MCH_CODE", "title": "Componente", "default": true },
  { "name": "ORG_CODE", "title": "Org Mant", "default": true },
  { "name": "TIPO_PARADA", "title": "Tipo parada", "default": true },
  { "name": "WORK_TYPE_ID", "title": "Tipo Trabajo", "default": true },
  { "name": "PRIORITY_ID", "title": "Prioridad", "default": true },
  { "name": "TAREA", "title": "Tarea", "default": true },
  { "name": "CATEGORY_ID", "title": "Clase Seg", "default": true },
  { "name": "REG_DATE", "title": "Fecha Registro", "default": true },
  { "name": "FIRMA_PAQ_TRAB", "title": "Firma paq trab", "default": true },
  { "name": "WORK_LEADER_SIGN", "title": "Resp.Tarea", "default": true },
  { "name": "CONFIRMACION_1", "title": "Confirmacion 1", "default": true },
  { "name": "PREPARED_BY", "title": "Planifica", "default": true },
  { "name": "COM_INT_PRO", "title": "Com int pro", "default": true },
  { "name": "MCH_LOC", "title": "Recinto", "default": true },
  { "name": "MCH_POS", "title": "Pos.en Tab.", "default": true },
  { "name": "COM_PLA_PRO", "title": "Com pla pro", "default": true },
  { "name": "COM_IMP_PLA", "title": "Com imp pla", "default": true },
  { "name": "COM_IMP_PRO", "title": "Com imp pro", "default": true },
  { "name": "REQ_PAQ_TAB", "title": "Requiere Paq Trabajo", "default": true },
  { "name": "PALABRA_CLAVE", "title": "Palabra clave", "default": true },
  { "name": "NOTAS_MOTIVO", "title": "Notas Motivo", "default": true },
  { "name": "EQUIPOS_INDISPONIBLES", "title": "Equipos Indisponibles", "default": true },
  { "name": "TIPO_PAQ_TRAB", "title": "Tipo paq trab", "default": true },
  { "name": "PERFORMED_ACTION_LO", "title": "Acción Ejecutada", "default": true },
  { "name": "ERR_DESCR", "title": "Directiva", "default": false },
  { "name": "ERR_DESCR_LO", "title": "Descrip. Fallo", "default": false },
  { "name": "VENDOR_NO", "title": "Contratista", "default": false },
  { "name": "PM_TYPE", "title": "PM_TYPE", "default": false },
  { "name": "PM_TYPE_DB", "title": "Tipo MP", "default": false },
  { "name": "REPORTED_BY_ID", "title": "REPORTED_BY_ID", "default": false },
  { "name": "REPORTED_BY", "title": "Reportado", "default": false },
  { "name": "ERR_DISCOVER_CODE", "title": "ERR_DISCOVER_CODE", "default": false },
  { "name": "ERR_SYMPTOM", "title": "ERR_SYMPTOM", "default": false },
  { "name": "CALL_CODE", "title": "Evento", "default": false },
  { "name": "COMPANY", "title": "COMPANY", "default": false },
  { "name": "COST_CENTER", "title": "COST_CENTER", "default": false },
  { "name": "OBJECT_NO", "title": "OBJECT_NO", "default": false },
  { "name": "CODE_C", "title": "Código C", "default": false },
  { "name": "CODE_D", "title": "Código D", "default": false },
  { "name": "CODE_G", "title": "Código G", "default": false },
  { "name": "CODE_H", "title": "Código H", "default": false },
  { "name": "CODE_I", "title": "Código I", "default": false },
  { "name": "CODE_J", "title": "Código J", "default": false },
  { "name": "CODE_F", "title": "Código F", "default": false },
  { "name": "OP_STATUS_ID", "title": "Estado Operativo", "default": false },
  { "name": "TEST_POINT_ID", "title": "TEST_POINT_ID", "default": false },
  { "name": "WORK_MASTER_SIGN_ID", "title": "WORK_MASTER_SIGN_ID", "default": false },
  { "name": "WORK_MASTER_SIGN", "title": "Ejecutado por", "default": false },
  { "name": "WORK_LEADER_SIGN_ID", "title": "WORK_LEADER_SIGN_ID", "default": false },
  { "name": "PREPARED_BY_ID", "title": "PREPARED_BY_ID", "default": false },
  { "name": "AUTHORIZE_CODE", "title": "AUTHORIZE_CODE", "default": false },
  { "name": "PM_NO", "title": "PM_NO", "default": false },
  { "name": "PM_REVISION", "title": "PM_REVISION", "default": false },
  { "name": "PROJECT_NO", "title": "PROJECT_NO", "default": false },
  { "name": "WORK_DESCR_LO", "title": "Descripción Trabajo", "default": false },
  { "name": "PLAN_HRS", "title": "Tiempo Ejecución", "default": false },
  { "name": "ACTIVITY_SEQ", "title": "ACTIVITY_SEQ", "default": false },
  { "name": "PRE_ACCOUNTING_ID", "title": "PRE_ACCOUNTING_ID", "default": false },
  { "name": "LAST_ACTIVITY_DATE", "title": "LAST_ACTIVITY_DATE", "default": false },
  { "name": "REQUIRED_START_DATE", "title": "Inicio Requerido", "default": false },
  { "name": "REQUIRED_END_DATE", "title": "Última Finalización", "default": false },
  { "name": "REPAIR_FLAG", "title": "OT Reparación", "default": false },
  { "name": "CONTACT", "title": "CONTACT", "default": false },
  { "name": "PHONE_NO", "title": "PHONE_NO", "default": false },
  { "name": "CUSTOMER_NO", "title": "CUSTOMER_NO", "default": false },
  { "name": "STD_JOB_ID", "title": "STD_JOB_ID", "default": false },
  { "name": "ADDRESS_ID", "title": "ADDRESS_ID", "default": false },
  { "name": "REFERENCE_NO", "title": "REFERENCE_NO", "default": false },
  { "name": "FIXED_PRICE", "title": "FIXED_PRICE", "default": false },
  { "name": "FIXED_PRICE_DB", "title": "FIXED_PRICE_DB", "default": false },
  { "name": "FAULT_REP_FLAG", "title": "FAULT_REP_FLAG", "default": false },
  { "name": "QUOTATION_ID", "title": "QUOTATION_ID", "default": false },
  { "name": "CRITICALITY", "title": "Criticalidad", "default": false },
  { "name": "GROUP_ID", "title": "Grupo", "default": false },
  { "name": "CUST_ORDER_TYPE", "title": "CUST_ORDER_TYPE", "default": false },
  { "name": "CUST_ORDER_NO", "title": "CUST_ORDER_NO", "default": false },
  { "name": "PLANNED_MAN_HRS", "title": "Horas Man.", "default": false },
  { "name": "MCH_CODE_CONTRACT", "title": "Planta Objeto", "default": false },
  { "name": "MCH_CODE_DESCRIPTION", "title": "Descripción Objeto", "default": false },
  { "name": "CONNECTION_TYPE", "title": "CONNECTION_TYPE", "default": false },
  { "name": "CONNECTION_TYPE_DB", "title": "CONNECTION_TYPE_DB", "default": false },
  { "name": "RECEIVE_ORDER_NO", "title": "RECEIVE_ORDER_NO", "default": false },
  { "name": "REAL_S_DATE", "title": "F. Comienzo OT", "default": false },
  { "name": "ADDRESS1", "title": "ADDRESS1", "default": false },
  { "name": "ADDRESS2", "title": "ADDRESS2", "default": false },
  { "name": "ADDRESS3", "title": "ADDRESS3", "default": false },
  { "name": "ADDRESS4", "title": "ADDRESS4", "default": false },
  { "name": "ADDRESS5", "title": "ADDRESS5", "default": false },
  { "name": "ADDRESS6", "title": "ADDRESS6", "default": false },
  { "name": "ADDRESS7", "title": "ADDRESS7", "default": false },
  { "name": "CONTRACT_ID", "title": "CONTRACT_ID", "default": false },
  { "name": "LINE_NO", "title": "LINE_NO", "default": false },
  { "name": "AGREEMENT_ID", "title": "AGREEMENT_ID", "default": false },
  { "name": "CURRENCY_CODE", "title": "CURRENCY_CODE", "default": false },
  { "name": "SCHEDULING_CONSTRAINTS", "title": "SCHEDULING_CONSTRAINTS", "default": false },
  { "name": "SCHEDULING_CONSTRAINTS_DB", "title": "SCHEDULING_CONSTRAINTS_DB", "default": false },
  { "name": "OBJID", "title": "OBJID", "default": false },
  { "name": "OBJVERSION", "title": "OBJVERSION", "default": false },
  { "name": "OBJSTATE", "title": "OBJSTATE", "default": false },
  { "name": "OBJEVENTS", "title": "OBJEVENTS", "default": false },
  { "name": "TEMP_MOB_WO", "title": "TEMP_MOB_WO", "default": false },
  { "name": "GENERA_EVENTO", "title": "GENERA_EVENTO", "default": false },
  { "name": "REQUIERE_ANALISIS", "title": "REQUIERE_ANALISIS", "default": false },
  { "name": "REQUIERE_QC", "title": "REQUIERE_QC", "default": false },
  { "name": "CATEGORY_DESC", "title": "CATEGORY_DESC", "default": false },
  { "name": "MCH_TYPE", "title": "MCH_TYPE", "default": false },
  { "name": "MCH_TYPE_DESC", "title": "MCH_TYPE_DESC", "default": false },
  { "name": "PLANNED_WEEK", "title": "PLANNED_WEEK", "default": false },
  { "name": "COM_MAN_PRO", "title": "COM_MAN_PRO", "default": false },
  { "name": "COM_MAN", "title": "COM_MAN", "default": false },
  { "name": "COM_INT_MAN", "title": "COM_INT_MAN", "default": false },
  { "name": "OT_REPROGRAMADA", "title": "OT_REPROGRAMADA", "default": false },
  { "name": "OT_ESTADO_ANT", "title": "OT_ESTADO_ANT", "default": false },
  { "name": "COM_IMP_ARE", "title": "COM_IMP_ARE", "default": false },
  { "name": "FECHA_RECHEQUEO", "title": "FECHA_RECHEQUEO", "default": false },
  { "name": "CONFIRMACION_2", "title": "CONFIRMACION_2", "default": false },
  { "name": "CRITERIO_SEG", "title": "CRITERIO_SEG", "default": false },
  { "name": "AGRUP_PROG", "title": "AGRUP_PROG", "default": false },
  { "name": "OPCION_PP", "title": "OPCION_PP", "default": false },
  { "name": "ORDER_GANTT", "title": "ORDER_GANTT", "default": false },
  { "name": "VB_PLA", "title": "VB_PLA", "default": false },
  { "name": "ANTIGUEDAD", "title": "ANTIGUEDAD", "default": false },
  { "name": "PLAZO_PLANIF", "title": "PLAZO_PLANIF", "default": false },
  { "name": "MANO_OBRA", "title": "MANO_OBRA", "default": false },
  { "name": "COMENT_OTRAS_AREAS", "title": "COMENT_OTRAS_AREAS", "default": false },
  { "name": "ORDEN_CAMBIO", "title": "ORDEN_CAMBIO", "default": false },
  { "name": "ETAPA", "title": "ETAPA", "default": false },
  { "name": "RIESGO_NUCLEAR", "title": "Riesgo nuclear", "default": false },
  { "name": "RIESGO_RADIOLOG", "title": "Riesgo Radiológico", "default": false },
  { "name": "COMPLEJ_TAREA", "title": "Complejidad Tarea", "default": false },
  { "name": "EME", "title": "EME", "default": false },
  { "name": "SEGUIMIENTO_PROG", "title": "Seguimiento Prog", "default": false },
  { "name": "COMENT_SEG_PROG", "title": "Comentario Seg Prog", "default": false },
  { "name": "LOG_SEG_PROG", "title": "Log seg Prog", "default": false },
  { "name": "FRECUENCIA", "title": "Frecuencia", "default": false },
  { "name": "DISP_PROC_TEC", "title": "DISP_PROC_TEC", "default": false },
  { "name": "REVISION_PAQ_TRAB", "title": "REVISION_PAQ_TRAB", "default": false },
  { "name": "SISTEMA", "title": "Sistema", "default": false },
  { "name": "REQUIERE_PPM", "title": "REQUIERE_PPM", "default": false },
  { "name": "ANALIZA_EVENTO", "title": "Analiza Evento", "default": false },
  { "name": "WO_NO_HIJAS", "title": "WO_NO_HIJAS", "default": false },
  { "name": "EQUIPO_MADRE", "title": "EQUIPO_MADRE", "default": false },
  { "name": "USUARIO_QC", "title": "USUARIO_QC", "default": false },
  { "name": "USUARIO_CREACION", "title": "Creado Por", "default": false },
  { "name": "LUNES", "title": "LUNES", "default": false },
  { "name": "MARTES", "title": "MARTES", "default": false },
  { "name": "MIERCOLES", "title": "MIERCOLES", "default": false },
  { "name": "JUEVES", "title": "JUEVES", "default": false },
  { "name": "VIERNES", "title": "VIERNES", "default": false },
  { "name": "SABADO", "title": "SABADO", "default": false },
  { "name": "DOMINGO", "title": "DOMINGO", "default": false },
  { "name": "FECHA_GRACIA", "title": "FECHA_GRACIA", "default": false },
  { "name": "FECHA_DIFERIMIENTO", "title": "Fecha Diferido", "default": false },
  { "name": "ESTADO_PREVENTIVO", "title": "Estado Preventivo", "default": false },
  { "name": "NOTAS_QC", "title": "NOTAS_QC", "default": false },
  { "name": "TIENE_NOTAS_QC", "title": "TIENE_NOTAS_QC", "default": false },
  { "name": "NOTAS_ING", "title": "NOTAS_ING", "default": false },
  { "name": "TIENE_NOTAS_ING", "title": "TIENE_NOTAS_ING", "default": false },
  { "name": "LIBERACION_PR", "title": "LIBERACION_PR", "default": false },
  { "name": "SOL_SPC", "title": "SOL_SPC", "default": false },
  { "name": "EST_PLA_SPC", "title": "EST_PLA_SPC", "default": false },
  { "name": "SECCION_SPC", "title": "SECCION_SPC", "default": false },
  { "name": "OBS_SPC", "title": "OBS_SPC", "default": false },
  { "name": "LOG_OBS_SPC", "title": "LOG_OBS_SPC", "default": false },
  { "name": "ORIGEN_SPC", "title": "ORIGEN_SPC", "default": false },
  { "name": "LUG_EJEC_SPC", "title": "LUG_EJEC_SPC", "default": false },
  { "name": "REQUIERE_TARJETA", "title": "REQUIERE_TARJETA", "default": false },
  { "name": "OBS_TARJETA", "title": "OBS_TARJETA", "default": false },
  { "name": "TARJETA_RETIRADA", "title": "TARJETA_RETIRADA", "default": false },
  { "name": "NOTAS_CONC", "title": "NOTAS_CONC", "default": false },
  { "name": "TEST_RESULT", "title": "TEST_RESULT", "default": false },
  { "name": "TEST_COMMENT", "title": "TEST_COMMENT", "default": false },
  { "name": "OK_ING", "title": "OK_ING", "default": false },
  { "name": "OPO_D", "title": "OPO_D", "default": false },
  { "name": "OPO_A", "title": "OPO_A", "default": false },
  { "name": "ALARA", "title": "ALARA", "default": false },
  { "name": "TESTNUMBER", "title": "TESTNUMBER", "default": false },
  { "name": "SEGUIMIENTO", "title": "SEGUIMIENTO", "default": false },
  { "name": "FIRMA_EVALUADOR", "title": "FIRMA_EVALUADOR", "default": false },
  { "name": "NOVEDAD_SEMANAL", "title": "NOVEDAD_SEMANAL", "default": false }
]
var colActivas = ["WO_NO", "ERR_DESCR", "ERR_DESCR_LO", "PLAN_S_DATE", "VENDOR_NO", "PM_TYPE", "PM_TYPE_DB", "REPORTED_BY_ID", "REPORTED_BY", "PRIORITY_ID", "ORG_CODE", "ERR_DISCOVER_CODE", "ERR_SYMPTOM", "WORK_TYPE_ID", "CALL_CODE", "COMPANY", "COST_CENTER", "OBJECT_NO", "CODE_C", "CODE_D", "CODE_G", "CODE_H", "CODE_I", "CODE_J", "CODE_F", "CONTRACT", "MCH_CODE", "OP_STATUS_ID", "TEST_POINT_ID", "WORK_MASTER_SIGN_ID", "WORK_MASTER_SIGN", "WORK_LEADER_SIGN_ID", "WORK_LEADER_SIGN", "PREPARED_BY_ID", "PREPARED_BY", "AUTHORIZE_CODE", "PM_NO", "PM_REVISION", "PROJECT_NO", "REG_DATE", "PLAN_F_DATE", "WORK_DESCR_LO", "PLAN_HRS", "ACTIVITY_SEQ", "PRE_ACCOUNTING_ID", "LAST_ACTIVITY_DATE", "REQUIRED_START_DATE", "REQUIRED_END_DATE", "PERFORMED_ACTION_LO", "REPAIR_FLAG", "CONTACT", "PHONE_NO", "CUSTOMER_NO", "STD_JOB_ID", "ADDRESS_ID", "REFERENCE_NO", "FIXED_PRICE", "FIXED_PRICE_DB", "FAULT_REP_FLAG", "QUOTATION_ID", "CRITICALITY", "GROUP_ID", "CUST_ORDER_TYPE", "CUST_ORDER_NO", "PLANNED_MAN_HRS", "MCH_CODE_CONTRACT", "MCH_CODE_DESCRIPTION", "CONNECTION_TYPE", "CONNECTION_TYPE_DB", "RECEIVE_ORDER_NO", "REAL_S_DATE", "REAL_F_DATE", "ADDRESS1", "ADDRESS2", "ADDRESS3", "ADDRESS4", "ADDRESS5", "ADDRESS6", "ADDRESS7", "CONTRACT_ID", "LINE_NO", "AGREEMENT_ID", "CURRENCY_CODE", "SCHEDULING_CONSTRAINTS", "SCHEDULING_CONSTRAINTS_DB", "OBJID", "OBJVERSION", "OBJSTATE", "OBJEVENTS", "STATE", "TEMP_MOB_WO", "GENERA_EVENTO", "REQUIERE_ANALISIS", "REQUIERE_QC", "CATEGORY_ID", "CATEGORY_DESC", "MCH_TYPE", "MCH_TYPE_DESC", "PLANNED_WEEK", "REQ_PAQ_TAB", "TIPO_PARADA", "COM_PLA_PRO", "COM_MAN_PRO", "COM_MAN", "COM_INT_MAN", "OT_REPROGRAMADA", "OT_ESTADO_ANT", "COM_INT_PLA", "COM_IMP_PLA", "COM_INT_PRO", "COM_IMP_PRO", "COM_IMP_ARE", "FECHA_RECHEQUEO", "CONFIRMACION_1", "CONFIRMACION_2", "CRITERIO_SEG", "AGRUP_PROG", "OPCION_PP", "PALABRA_CLAVE", "FIRMA_PAQ_TRAB", "ORDER_GANTT", "VB_PLA", "SUBESTADO_PLANIF", "ANTIGUEDAD", "PLAZO_PLANIF", "TAREA", "MANO_OBRA", "COMENT_OTRAS_AREAS", "ORDEN_CAMBIO", "ETAPA", "RIESGO_NUCLEAR", "RIESGO_RADIOLOG", "COMPLEJ_TAREA", "EME", "SEGUIMIENTO_PROG", "COMENT_SEG_PROG", "LOG_SEG_PROG", "TIPO_PAQ_TRAB", "FRECUENCIA", "DISP_PROC_TEC", "REVISION_PAQ_TRAB", "SISTEMA", "MCH_LOC", "MCH_POS", "REQUIERE_PPM", "ANALIZA_EVENTO", "WO_NO_MADRE", "WO_NO_HIJAS", "EQUIPO_MADRE", "USUARIO_QC", "USUARIO_CREACION", "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADO", "DOMINGO", "FECHA_GRACIA", "FECHA_DIFERIMIENTO", "ESTADO_PREVENTIVO", "NOTAS_QC", "TIENE_NOTAS_QC", "NOTAS_ING", "TIENE_NOTAS_ING", "LIBERACION_PR", "SOL_SPC", "EST_PLA_SPC", "SECCION_SPC", "OBS_SPC", "LOG_OBS_SPC", "ORIGEN_SPC", "LUG_EJEC_SPC", "REQUIERE_TARJETA", "OBS_TARJETA", "TARJETA_RETIRADA", "NOTAS_CONC", "TEST_RESULT", "TEST_COMMENT", "OK_ING", "OPO_D", "OPO_A", "ALARA", "TESTNUMBER", "SEGUIMIENTO", "FIRMA_EVALUADOR", "NOTAS_MOTIVO", "EQUIPOS_INDISPONIBLES", "NOVEDAD_SEMANAL"]
var no = ["FIRMA_EVALUADOR", "SEGUIMIENTO", "TESTNUMBER", "NOTAS_CONC", "DOMINGO", "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADO", "OT_ESTADO_ANT", "OT_REPROGRAMADA", "TEMP_MOB_WO", "STATE", "OBJEVENTS", "OBJSTATE", "SCHEDULING_CONSTRAINTS_DB", "SCHEDULING_CONSTRAINTS", "CURRENCY_CODE", "RECEIVE_ORDER_NO", "CUST_ORDER_NO", "CUST_ORDER_TYPE", "GROUP_ID", "CRITICALITY", "STD_JOB_ID"]
var colHistorical = ["WO_NO", "REG_DATE", "ERR_DESCR", "PLAN_S_DATE", "PLAN_F_DATE", "REAL_S_DATE", "REAL_F_DATE", "WORK_DONE", "WORK_DESCR_LO", "PLAN_MEN", "PLAN_HRS", "COMPANY", "ACTIVITY_SEQ", "PLAN_F_WEEK", "PRE_ACCOUNTING_ID", "NOTE", "LAST_ACTIVITY_DATE", "NOTE_ID", "REQUIRED_START_DATE", "REQUIRED_END_DATE", "PM_TYPE", "PM_TYPE_DB", "ERR_CAUSE", "PERFORMED_ACTION_ID", "COST_CENTER", "OBJECT_NO", "CODE_C", "CODE_D", "CODE_G", "CODE_H", "CODE_I", "CODE_J", "CODE_F", "PROJECT_NO", "ERR_SYMPTOM", "ERR_DISCOVER_CODE", "WORK_TYPE_ID", "PRIORITY_ID", "ERR_TYPE", "ACTION_CODE_ID", "ERR_CLASS", "OP_STATUS_ID", "CALL_CODE", "WORK_LEADER_SIGN_ID", "WORK_LEADER_SIGN", "WORK_MASTER_SIGN_ID", "WORK_MASTER_SIGN", "PREPARED_BY_ID", "PREPARED_BY", "REPORTED_BY_ID", "REPORTED_BY", "AUTHORIZE_CODE", "PM_NO", "PM_REVISION", "CONTRACT", "MCH_CODE", "TEST_POINT_ID", "ORG_CODE", "VENDOR_NO", "REPAIR_FLAG", "CONTACT", "PHONE_NO", "ADDRESS_ID", "REFERENCE_NO", "FIXED_PRICE", "FIXED_PRICE_DB", "AGREEMENT_ID", "CUSTOMER_NO", "QUOTATION_ID", "FAULT_REP_FLAG", "GENERATE_NOTE", "GENERATE_NOTE_DB", "PLANNED_MAN_HRS", "MCH_CODE_CONTRACT", "CONNECTION_TYPE", "CONNECTION_TYPE_DB", "MCH_CODE_DESCRIPTION", "WO_STATUS_ID", "CONTRACT_ID", "LINE_NO", "ERR_DESCR_LO", "ERR_CAUSE_LO", "PERFORMED_ACTION_LO", "ADDRESS1", "ADDRESS2", "ADDRESS3", "ADDRESS4", "ADDRESS5", "ADDRESS6", "ADDRESS7", "GENERA_EVENTO", "REQUIERE_ANALISIS", "REQUIERE_QC", "REQ_PAQ_TAB", "TIPO_PARADA", "COM_PLA_PRO", "COM_MAN_PRO", "COM_MAN", "COM_INT_MAN", "COM_INT_PLA", "COM_IMP_PLA", "COM_INT_PRO", "COM_IMP_PRO", "COM_IMP_ARE", "FECHA_RECHEQUEO", "CONFIRMACION_1", "CONFIRMACION_2", "CRITERIO_SEG", "AGRUP_PROG", "OPCION_PP", "PALABRA_CLAVE", "FIRMA_PAQ_TRAB", "ORDER_GANTT", "VB_PLA", "SUBESTADO_PLANIF", "RIESGO_NUCLEAR", "RIESGO_RADIOLOG", "COMPLEJ_TAREA", "EME", "SEGUIMIENTO_PROG", "COMENT_SEG_PROG", "LOG_SEG_PROG", "TIPO_PAQ_TRAB", "CATEGORY_ID", "CATEGORY_DESC", "MANO_OBRA", "COMENT_OTRAS_AREAS", "ORDEN_CAMBIO", "ETAPA", "PLAZO_PLANIF", "TAREA", "MCH_TYPE", "MCH_TYPE_DESC", "PLANNED_WEEK", "ANTIGUEDAD", "FRECUENCIA", "DISP_PROC_TEC", "REVISION_PAQ_TRAB", "SISTEMA", "REQUIERE_PPM", "MCH_LOC", "MCH_POS", "ANALIZA_EVENTO", "WO_NO_MADRE", "WO_NO_HIJAS", "EQUIPO_MADRE", "USUARIO_QC", "USUARIO_CREACION", "FECHA_GRACIA", "FECHA_DIFERIMIENTO", "ESTADO_PREVENTIVO", "SEQ_NO", "NOTAS_QC", "TIENE_NOTAS_QC", "LIBERACION_PR", "SOL_SPC", "EST_PLA_SPC", "SECCION_SPC", "OBS_SPC", "LOG_OBS_SPC", "ORIGEN_SPC", "LUG_EJEC_SPC", "REQUIERE_TARJETA", "OBS_TARJETA", "TARJETA_RETIRADA", "NOTAS_ING", "TIENE_NOTAS_ING", "TEST_RESULT", "TEST_COMMENT", "OK_ING", "OPO_D", "OPO_A", "ALARA", "NOTAS_MOTIVO", "EQUIPOS_INDISPONIBLES", "NOVEDAD_SEMANAL", "OBJID", "OBJVERSION"]
var colsSi = cols.filter(c => no.indexOf(c.name) == -1)
console.log(cols.length)
console.log(colsSi.length)

// FISTORICAL STATE: CASE WO_STATUS_ID WHEN 'FINISHED' THEN 'Finalizado' ELSE 'Cancelado' END AS STATE
